import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {envFile,json,sandbox} from './lib.mjs';
export const ids=['ramideltoro'];
const site='fcc652ed-b756-4d51-95e7-67e841429ea9';
async function api(route,raw=false){const {NETLIFY_AUTH_TOKEN:token}=await envFile('/etc/observe-recovery/credentials.env');if(!token)throw Error('Netlify recovery credential unavailable');const r=await fetch('https://api.netlify.com/api/v1'+route,{headers:{Authorization:'Bearer '+token,...(raw?{'Content-Type':'application/vnd.bitballoon.v1.raw'}:{})},signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error('Netlify recovery source unavailable: '+r.status);return raw?Buffer.from(await r.arrayBuffer()):r.json();}
export function safeFile(p){if(typeof p!=='string'||!p.startsWith('/')||p.startsWith('//')||p.includes('\\')||p.split('/').some(x=>x==='..'||x==='.')||p.includes('\0'))throw Error('Unsafe deployment path');return p.slice(1);}
export async function revision(){const s=await api('/sites/'+site);if(s.published_deploy?.state!=='ready')throw Error('Published deployment unavailable');return s.published_deploy.id;}
export async function capture(id,revision,dir){const [deploy,files,functions,configuration]=await Promise.all([api('/deploys/'+revision),api('/deploys/'+revision+'/files'),api('/deploys/'+revision+'/functions'),api('/sites/'+site)]);
 if(deploy.site_id!==site||deploy.state!=='ready'||functions.length||deploy.edge_functions_present||deploy.required_functions?.length)throw Error('Deployment requires unsupported dynamic recovery');
 if(!Array.isArray(files)||!files.some(f=>f.path==='/index.html'))throw Error('Deployment inventory incomplete');
 const origin=new URL(deploy.deploy_ssl_url);if(origin.protocol!=='https:'||!origin.hostname.endsWith('.netlify.app'))throw Error('Invalid immutable deployment URL');
 await fs.mkdir(dir+'/site');
 for(const f of files){const relative=safeFile(f.path);if(!/^[a-f0-9]{40}$/.test(f.sha))throw Error('Missing deployment checksum');const bytes=await api('/deploys/'+revision+'/files'+f.path.split('/').map(encodeURIComponent).join('/'),true);if(createHash('sha1').update(bytes).digest('hex')!==f.sha)throw Error('Deployment file checksum mismatch');const target=path.join(dir,'site',relative);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,bytes,{mode:0o600});}
 await json(dir+'/deployment.json',{id,revision,provider:'netlify',site,files:files.map(({path,sha,size})=>({path,sha,size})),configuration:{customDomain:configuration.custom_domain,domainAliases:configuration.domain_aliases,forceSsl:configuration.force_ssl,buildSettings:configuration.build_settings&&{repoUrl:configuration.build_settings.repo_url,dir:configuration.build_settings.dir,cmd:configuration.build_settings.cmd}},scope:'Complete static deployed artifact and hosting configuration; no server functions'});
}
export async function restore(id,dir){await fs.writeFile(dir+'/verify-netlify.mjs',`import fs from 'node:fs/promises';import http from 'node:http';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';const manifest=JSON.parse(await fs.readFile('/work/deployment.json'));assert(manifest.files.length>0);for(const f of manifest.files){const b=await fs.readFile('/work/site'+f.path);assert.equal(createHash('sha1').update(b).digest('hex'),f.sha);}const paths=new Set(manifest.files.map(f=>f.path));const server=http.createServer(async(req,res)=>{const p=decodeURIComponent(req.url==='/'?'/index.html':req.url);if(!paths.has(p)){res.writeHead(404);res.end();return;}res.end(await fs.readFile('/work/site'+p));});await new Promise(r=>server.listen(8080,'127.0.0.1',r));try{for(const p of paths){const r=await fetch('http://127.0.0.1:8080'+p);assert.equal(r.status,200);assert((await r.arrayBuffer()).byteLength>0);}await fs.writeFile('/work/result.json',JSON.stringify({verifiedFiles:paths.size,scope:manifest.scope}));}finally{server.close();}`);await sandbox(dir,['node','/work/verify-netlify.mjs']);}
