import fs from 'node:fs/promises';
import {Readable} from 'node:stream';
import {createWriteStream} from 'node:fs';
import {pipeline} from 'node:stream/promises';
import {run,writable,sandbox,json} from './lib.mjs';
export const sites={'kubequest-wiki':'kubequest-wiki','local-wiki':'local-server-wiki','nutsnews-wiki':'nutsnews-docs','legacy-personal':'rami-deltoro.github.io'};
async function api(repo,route,token){const r=await fetch(`https://api.github.com/repos/ramideltoro/${repo}${route}`,{headers:{Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28'},signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error('GitHub recovery source unavailable: '+r.status);return r;}
export async function revision(id,token){const repo=sites[id];if(id==='legacy-personal'){const b=await(await api(repo,'/pages/builds/latest',token)).json();if(b.status!=='built')throw Error('Pages build not ready');return b.commit;}
 const ds=await(await api(repo,'/deployments?environment=github-pages&per_page=10',token)).json();for(const d of ds){const ss=await(await api(repo,`/deployments/${d.id}/statuses`,token)).json();if(ss.some(s=>s.state==='success'))return d.sha;}throw Error('No successful Pages deployment');}
export async function capture(id,revision,dir,token){const repo=sites[id],r=await api(repo,'/tarball/'+revision,token);await pipeline(Readable.fromWeb(r.body),createWriteStream(dir+'/source.tar.gz',{mode:0o600}));await fs.mkdir(dir+'/source');await run('tar',['xzf',dir+'/source.tar.gz','--strip-components=1','--no-same-owner','-C',dir+'/source']);const pages=await(await api(repo,'/pages',token)).json();await json(dir+'/deployment.json',{repository:'ramideltoro/'+repo,revision,provider:'github-pages',configuration:{source:pages.source,build_type:pages.build_type,cname:pages.cname,https_enforced:pages.https_enforced}});}
export async function prepare(id,dir){if(id==='legacy-personal')return;await writable(dir);await sandbox(dir+'/source',['/bin/bash','-c','npm ci --ignore-scripts --no-audit --no-fund'],{network:true,timeout:900000});}
export async function restore(id,dir){const revision=JSON.parse(await fs.readFile(dir+'/deployment.json')).revision;if(!/^[a-f0-9]{40}$/.test(revision))throw Error('Invalid deployed revision');if(id!=='legacy-personal')await sandbox(dir,['/usr/bin/env','GITHUB_SHA='+revision,'/bin/bash','-c','cd source && npm run build'],{timeout:900000});
 const candidates=id==='legacy-personal'?['source']:['source/dist','source/_site','source/site'];let site;for(const p of candidates)if(await fs.stat(dir+'/'+p+'/index.html').catch(()=>null)){site=p;break;}if(!site)throw Error('Reconstructed entry page missing');
 await fs.writeFile(dir+'/verify-static.mjs',`import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import assert from 'node:assert/strict';
const root='/work/${site}';const files=[];async function walk(d){for(const e of await fs.readdir(d,{withFileTypes:true})){if(e.name.startsWith('.'))continue;const p=path.join(d,e.name);if(e.isDirectory())await walk(p);else files.push(p.slice(root.length));}}await walk(root);
const pages=files.filter(p=>p.endsWith('.html')).slice(0,4),assets=files.filter(p=>/\\.(css|js|png|svg)$/.test(p)).slice(0,4);assert(pages.length&&assets.length,'Pages and assets required');
const server=http.createServer(async(req,res)=>{try{const p=path.resolve(root,'.'+decodeURIComponent(req.url));if(!p.startsWith(root+'/'))throw Error();res.end(await fs.readFile(p));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(8080,'127.0.0.1',r));try{for(const p of [...pages,...assets]){const r=await fetch('http://127.0.0.1:8080'+encodeURI(p));assert.equal(r.status,200);assert((await r.arrayBuffer()).byteLength>0);}await fs.writeFile('/work/result.json',JSON.stringify({pages,assets}));}finally{server.close();}
`);await sandbox(dir,['node','/work/verify-static.mjs']);}
