import fs from 'node:fs';
const [portal,wiki]=process.argv.slice(2);
const directory=portal+'/config/published';
const dashboards=fs.existsSync(directory)?fs.readdirSync(directory).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(fs.readFileSync(directory+'/'+f,'utf8'))):[];
const links=dashboards.map(d=>`- [${d.title.replace(/[\[\]\n]/g,' ')}](https://observe.ramideltoro.com/#dashboard/${encodeURIComponent(d.uid)}) — ${d.panels.length} panels`).join('\n')||'No dashboards have been published yet.';
const file=wiki+'/src/data/topics.json',topics=JSON.parse(fs.readFileSync(file,'utf8'));
const topic={slug:'published-dashboards',title:'Published dashboards',group:'Operations',icon:'◈',description:'Automatically synchronized catalog of reviewed workspace dashboards.',summary:`## Your published views\nThese dashboards were created as owner copies and published through reviewed Git pull requests. Anyone can read their sanitized metric views without signing in.\n\n## Dashboard catalog\n${links}\n\n## Make a change\nSign in with Google to edit the owner copy, then publish another reviewed version. Public visitors cannot change saved dashboards.`,technical:`## Release coordination\nThis catalog is generated from config/published in the observability repository. The deployment pipeline updates it only when the deployed-to-requested diff contains published dashboard files and the previous wiki fingerprints match. Other code changes retain the normal documentation gate.\n\n## Published dashboards\n${links}\n\n## Query boundary\nPublished panels use registered query identifiers and native presentation defaults. Cloud credentials, private links, arbitrary template parameters and raw log evidence are not copied into public definitions.`,expert:`## Why publication updates documentation\nA dashboard-only publish should not require a separate manual documentation edit. The coordinator verifies that no application or infrastructure code changed, confirms the existing documentation matches the previous release, then generates the catalog and records the new fingerprint before activation.\n\n## Reviewed catalog\n${links}\n\n## Ownership and rollback\nPublic definitions use new identities, leaving editable owner copies untouched. Git review controls publication. Ordinary source changes cannot use this narrow synchronization exception, and a failed documentation build prevents activation.`};
const index=topics.findIndex(t=>t.slug===topic.slug);if(index<0)topics.push(topic);else topics[index]=topic;
fs.writeFileSync(file,JSON.stringify(topics,null,2)+'\n');
